### ISSUE TITLE
Failed to build on linux 6.14

### ISSUE THREAD

**Issue by Lyxot** [xairy/raw-gadget#85]
as of kernel 6.12-rc2 asm/unaligned.h have been moved to linux/unaligned.h

logs:
```
make -C /lib/modules/6.14.8-2-pve/build M=/root/raw-gadget/dummy_hcd SUBDIRS=/root/raw-gadget/dummy_hcd modules
make[1]: Entering directory '/usr/src/linux-headers-6.14.8-2-pve'
make[2]: Entering directory '/root/raw-gadget/dummy_hcd'
  CC [M]  dummy_hcd.o
dummy_hcd.c:45:10: fatal error: asm/unaligned.h: No such file or directory
   45 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.14.8-2-pve/scripts/Makefile.build:207: dummy_hcd.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.14.8-2-pve/Makefile:2001: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.14.8-2-pve/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/root/raw-gadget/dummy_hcd'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.14.8-2-pve'
make: *** [Makefile:8: default] Error 2
```

**Comment by Lyxot** [comment]
Everything works fine on linux 6.14 with this patch:
```
diff --git a/dummy_hcd/dummy_hcd.c b/dummy_hcd/dummy_hcd.c
index f37b0d8..81c4ce8 100644
--- a/dummy_hcd/dummy_hcd.c
+++ b/dummy_hcd/dummy_hcd.c
@@ -42,7 +42,7 @@
 #include <asm/byteorder.h>
 #include <linux/io.h>
 #include <asm/irq.h>
-#include <asm/unaligned.h>
+#include <linux/unaligned.h>
 
 #define DRIVER_DESC    "USB Host+Gadget Emulator"
 #define DRIVER_VERSION "02 May 2005"
@@ -1151,7 +1151,7 @@ static int dummy_udc_resume(struct platform_device *pdev)
 
 static struct platform_driver dummy_udc_driver = {
        .probe          = dummy_udc_probe,
-       .remove_new     = dummy_udc_remove,
+       .remove         = dummy_udc_remove,
        .suspend        = dummy_udc_suspend,
        .resume         = dummy_udc_resume,
        .driver         = {
@@ -2757,7 +2757,7 @@ static int dummy_hcd_resume(struct platform_device *pdev)
 
 static struct platform_driver dummy_hcd_driver = {
        .probe          = dummy_hcd_probe,
-       .remove_new     = dummy_hcd_remove,
+       .remove         = dummy_hcd_remove,
        .suspend        = dummy_hcd_suspend,
        .resume         = dummy_hcd_resume,
        .driver         = {
```
But I can't be sure about it on earlier versions.
